### ISSUE TITLE
Create rat mesh

### ISSUE THREAD

**Issue by RossMcConeghy** [TwoClunkers/Clunk-Genesis#11]
Create rat mesh

**Comment by RossMcConeghy** [comment]
In progress:
![rat-remesh](https://cloud.githubusercontent.com/assets/4841483/6882620/f2fae4a6-d548-11e4-9140-16f8b36682e5.png)

**Comment by RossMcConeghy** [comment]
Mesh is complete, on to Texturing!

**Comment by jesterstud** [comment]
Man, I didn't get nothin' done. too busy entertaining the fam. But hey, we
gonna have chickens...:)
