### ISSUE TITLE
Create AnimatorController in Unity

### ISSUE THREAD

**Issue by RossMcConeghy** [TwoClunkers/Clunk-Genesis#14]

**Comment by RossMcConeghy** [comment]
Done.
Hmm.. will need an AI to interface with this AC.
![image](https://cloud.githubusercontent.com/assets/4841483/6883885/44ea2cc6-d581-11e4-8912-a5ad89340907.png)

**Comment by RossMcConeghy** [comment]
![image](https://cloud.githubusercontent.com/assets/4841483/6883920/751741ba-d584-11e4-89ee-5ab021fbd88b.png)

**Comment by jesterstud** [comment]
did you Git it? did ya did ya?
